apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-client
        image: rmeharg/rabbitmq-client:dev
        imagePullPolicy: Always
        command: ["send",  "amqp://user:CHANGEME@rabbitmq.rabbitmq.svc.cluster.local:5672", "300"]
      restartPolicy: Never
  backoffLimit: 4
